Repository AY2425S1-CS2103T-T14-3/tp, pull requests merged in 2024-11, with the labels that each got.

#180 Update UG
  docs/UserGuide.md
  docs/images/viewResult.png
Labels: alpha-bug

#181 Update UG
  docs/UserGuide.md
Labels: alpha-bug

#182 Update UG
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: alpha-bug

#186 Update conditional path for handleHelp
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, alpha-bug

#187 Add the info box for view
  README.md
  docs/UserGuide.md
Labels: priority.Low, alpha-bug

#194 Update UG
  docs/DeveloperGuide.md
Labels: priority.Low

#198 Update Documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
  docs/images/limyuquan.png
  docs/images/meowloid.png
Labels: priority.High, severity.Low, alpha-bug

#200 Add testing for edit DG
  docs/DeveloperGuide.md
Labels: priority.High

#201 Add testing for find and view DG
  docs/DeveloperGuide.md
Labels: priority.High

#206 Update UG
  docs/UserGuide.md
Labels: priority.Medium

#215 Update UG (Page Break, VRN)
  docs/UserGuide.md
Labels: priority.High

#264 Fixing bugs from PE-D and update some code quality stuff
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/Ui.png
  src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#279 Finalise User Guide
  docs/UserGuide.md
Labels: priority.High
