Repository AY2425S1-CS2103T-T14-3/tp, pull requests merged in 2024-10, with the labels that each got.

#31 Update README and Site
  README.md
  docs/_markbind/layouts/default.md
  docs/images/Ui.png
Labels: priority.Medium

#41 Create DG Use Case
  README.md
  docs/DeveloperGuide.md
Labels: priority.Medium

#34 Add user stories to DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Medium

#45 Add Glossary
  docs/DeveloperGuide.md
Labels: priority.High

#49 Create Car Class
  src/main/java/seedu/address/model/car/Car.java
  src/main/java/seedu/address/model/car/CarMake.java
  src/main/java/seedu/address/model/car/CarModel.java
  src/main/java/seedu/address/model/car/Vin.java
  src/main/java/seedu/address/model/car/Vrn.java
  src/main/java/seedu/address/model/car/exceptions/CarNotFoundException.java
  src/main/java/seedu/address/model/car/exceptions/DuplicateCarException.java
  src/test/java/seedu/address/model/car/CarMakeTest.java
  src/test/java/seedu/address/model/car/CarModelTest.java
  src/test/java/seedu/address/model/car/CarTest.java
  src/test/java/seedu/address/model/car/VinTest.java
  src/test/java/seedu/address/model/car/VrnTest.java
Labels: priority.High

#54 Add user profile and value proposition
  docs/DeveloperGuide.md
Labels: priority.High

#58 Edit client feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditCarDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#59 Add View Client Feature
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewClientWindow.java
  src/main/resources/view/ViewClientWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High

#57 Add frontend support for add-client
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/ListClientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
Labels: priority.High

#70 Update Command Class names and Command Words
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/ListClientCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditClientCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewClientCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ListClientCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/testutil/EditCarDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium

#64 Add find vrn feature
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.High

#77 Update GUI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ViewClientWindow.java
  src/main/resources/images/mater.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ViewClientWindow.fxml
Labels: priority.High

#79 Edit client missing car bug
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
Labels: type.Bug, priority.High

#80 Change all occurences of tag to issue
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditClientCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/issue/Issue.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedIssue.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ViewClientWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/issue/IssueTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#100 Update DG Proposed Implementation for View Client and DG Use Cases
  docs/DeveloperGuide.md
  docs/diagrams/ViewClientActivityDiagram.puml
  docs/diagrams/ViewClientSequenceDiagram.puml
Labels: priority.High

#101 Main Window GUI Bug Fix
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, severity.Low

#103 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#113 Reformat diagram
  docs/diagrams/UiClassDiagram.puml
Labels: priority.Medium

#119 Add Check In/ Out Feature
  src/main/java/seedu/address/logic/commands/CheckClientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckClientCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CheckClientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckClientCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#121 Add check-client section to dg and add AddressBookParser test
  .gitignore
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/CheckClientActivityDiagram.puml
  docs/diagrams/CheckClientSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/team/johndoe.md
  docs/team/tahirhairul.md
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#134 Add delete-car feature
  src/main/java/seedu/address/logic/commands/AddCarCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCarCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCarCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCarCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCarCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCarCommandParserTest.java
Labels: priority.High

#136 Simplify commands without ambiguity
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ViewClientActivityDiagram.puml
  docs/diagrams/ViewClientSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/DeleteCarCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/ListClientCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: severity.Low, alpha-bug

#130 Update Result Display
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCarCommand.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/CheckClientCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCarCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListClientCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCarCommandTest.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CheckClientCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCarCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteClientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewClientCommandTest.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#143 Update UG for Check feature
  docs/UserGuide.md
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
  docs/images/checkResult.png
  docs/images/findResult.png
  docs/images/johndoe.png
  docs/images/viewClientResult.png
  docs/images/viewResult.png
Labels: priority.High

#150 Fix bug
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/model/car/Car.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
Labels: type.Bug, priority.High

#141 Alpha Bug Fix (Result Display, DG, Check)
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCarCommand.java
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/CheckClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCarCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/model/car/Car.java
  src/main/java/seedu/address/model/car/CarMake.java
  src/main/java/seedu/address/model/car/CarModel.java
  src/main/java/seedu/address/model/car/Vin.java
  src/main/java/seedu/address/model/car/Vrn.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, severity.VeryLow

#151 Fix Delete Car Bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCarCommand.java
Labels: priority.High

#152 Add check in and out view
  src/main/java/seedu/address/ui/ViewClientWindow.java
  src/main/resources/view/ClientWindow.css
  src/main/resources/view/ViewClientWindow.fxml
Labels: priority.High

#154 Rename blankSlate var to EMPTY_SET_OF_ISSUES for style and readability
  src/main/java/seedu/address/logic/commands/DeleteCarCommand.java
Labels: priority.High

#156 Alpha Bug Fix II (Check, DG)
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/CheckClientCommand.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckClientCommandTest.java
Labels: severity.Low, alpha-bug

#162 Fix edge case
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCarCommandTest.java
  src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCarCommandTest.java
Labels: type.Bug, priority.High

#159 Limit fields to certain lengths
  docs/UserGuide.md
  src/main/java/seedu/address/model/car/CarMake.java
  src/main/java/seedu/address/model/car/CarModel.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/car/CarMakeTest.java
  src/test/java/seedu/address/model/car/CarModelTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.Medium, alpha-bug

#176 Update DG Implementation
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  docs/diagrams/ViewClientSequenceDiagram.puml
Labels: alpha-bug

#179 Add 3 lines
  docs/UserGuide.md
Labels: type.Tas

#178 Update ug
  docs/UserGuide.md
Labels: type.Enhancement
